---
title: "DT_Carga_Datos_Trafico"
output: html_document
author: "Mikel Uranga"
date: "22/10/2017"
---

```{r}
#Cargamos las librerias necesarias
library(readr)
library(dplyr)
```

```{r}
#Definimos las variables de control
#url: el link de descarga obtenido de la web #http://datos.madrid.es/sites/v/index.jsp?vgnextoid=33cb30c367e78410VgnVCM1000000b205a0aRCRD&vgnextchannel=374512b9ace9f310VgnVCM100000171f5a0aRCRD
#download_data: el nombre del fichero temporal donde alojar los datos en crudo
#file_path: la ruta al directorio de almacenamiento de los datos
#file_name: nombre de lficher ofinal

url <- "http://datos.madrid.es/egob/catalogo/208627-51-transporte-ptomedida-historico.zip"
download_data <- "rawData.csv"
file_path <- "~/RStudio/Dataton2017/datasets/trafico/"
file_name <- "201708_DatosTrafico.csv"
```


```{r}
# Definimos una variable con el nombre del fichero
fichero  <- paste0(tempfile(), ".zip")

# Y vemos el resultado
fichero

# Descargamos el fichero al ordenador en una ubicación temporal con la función 
download.file(url, destfile = fichero)
```

```{r}
#Guardamos los datos en crudo
write.csv(read_delim(fichero, ";", escape_double = FALSE, trim_ws = TRUE),paste(file_path, download_data, sep=''), row.names=FALSE)

```

```{r}
#Cargamos el fichero parseando los datos en el formato adecuado
data <- read_delim(paste(file_path, download_data, sep=''), ",", escape_double = FALSE, col_types = cols(fecha = col_datetime(format = "%Y-%m-%d %H:%M:%S")), 
    trim_ws = TRUE)
View(data)

```

```{r}
#Nos quedamos con lso registros de la M30
dataM30 <-  data %>% filter(tipo_elem ==  "PUNTOS MEDIDA M-30" )
```

```{r}
#Guardamos los datos finales y tratados en un fichero csv
write.csv(dataM30, paste(file_path, file_name, sep=''), row.names=FALSE)

```





