---
title: "DT_Descarga_Datos_Trafico_Completo"
output: html_document
author: "Mikel Uranga"
date: "22/10/2017"
---

```{r}
library(stringr)
library(readr)
```

```{r}
#Número de datasets disponible
N <- 46

#Se genera un contenedor de urls
#url <- data.frame(x = rnorm(N), y = runif(N))
rm(url)
rm(datos)

url <- data.frame(x = rnorm(N))
datos <- data.frame(x = rnorm(N))
```

```{r}
#Generamos y guardamos los enlaces 
for (link in c(0:N)){
 url_link <- str_replace_all(paste("http://datos.madrid.es/egob/catalogo/208627-", link,"-transporte-ptomedida-historico.zip" )," ", "")
 
url[link,] <- url_link
 
}
```

```{r}
# Definimos una variable con el nombre del fichero
fichero  <- paste0(tempfile(), ".zip")

# Y vemos el resultado
fichero


# Descargamos el fichero al ordenador en una ubicación temporal con la función 
#download.file()
#download.file(url, destfile = fichero)
```

```{r}
#Se crea una función para poder descargar ficheros de forma dinámica
writeCSVDyn <- function(d, env = parent.frame()) {
    write.csv(get(d, env = env),
              file = paste0('~/RStudio/Dataton2017/datasets/trafico/',d,".csv"),
              row.names = FALSE)
}
```


```{r}

for(i in 1:N){
  download.file(url[i,], destfile = fichero)
  assign(paste('Datos', i, sep=''), read_delim(fichero, ";", escape_double = FALSE, trim_ws = TRUE)) 
  writeCSVDyn(paste('Datos', i, sep=''))
  
}
```



