---
title: "Dt_Seleccion_Puntos_Medida"
output: html_document
---

```{r}
#Se cargan las librerias necesarias
library('CausalImpact')
library(readr)
library(dplyr)
library(imputeTS)
```

#Carga de Datos

```{r}
#Se utiliza el dataset de febrero del 2016 por ser un mes sin excesivas variaciones o festividades.
DatosTrafico1602 <- read_csv("~/RStudio/Dataton2017/datasets/trafico/201602_DatosTrafico.csv", 
    col_types = cols(fecha = col_datetime(format = " %Y-%m-%d  %H:%M:%S")))
#View(DatosTrafico1704)

```

#Descripción

```{r}
summary(DatosTrafico1602)
```

#Outliers

```{r}
#outliers Carga

outlier_carga <- boxplot.stats(DatosTrafico1602$carga)$out

boxplot(DatosTrafico1602$carga, main="carga", boxwex=0.1)

mtext(paste("Outliers: ", paste(outlier_carga, collapse=", ")), cex=0.6)
```


```{r}
#Agrupamos por punto de medida 
DatosTrafico1602 %>% 
  filter(carga %in% outlier_carga ) %>%
  group_by(identif) %>% 
  dplyr::summarise(n = n()) %>% 
  arrange(desc(n))  
```


```{r}
#Agrupamos por punto de medida no outliers
DatosTrafico1602 %>% 
  filter(!carga %in% outlier_carga ) %>%
  group_by(identif) %>% 
  dplyr::summarise(n = n()) %>% 
  arrange(desc(n))  
```

```{r}
#Guardamos los Puntos de Medida seleccionados 
PM_outliers_carga <- DatosTrafico1602 %>% 
  filter(carga %in% outlier_carga ) %>%
  group_by(identif) %>% 
  dplyr::summarise(n = n()) %>% 
  arrange(desc(n))  
```


```{r}
#Guardamos los Puntos de Medida no outliersseleccionados 
PM_no_outliers_carga <- DatosTrafico1602 %>% 
  filter(!identif %in% PM_outliers_carga$identif ) %>%
  filter(substr(identif,1,2)=="PM") %>%
  group_by(identif) %>% 
  dplyr::summarise(n = n()) %>% 
  arrange(desc(n))  
```


```{r}
#Seleccionamos 46 puntos aleatorios
PM_no_outliers_carga <- sample_n(PM_no_outliers_carga, 46)
```

```{r}
#Unimos los dos datasets
PM_seleccionados <- rbind(PM_outliers_carga,PM_no_outliers_carga)
```

```{r}
#Buscamos duplicados
n_occur <- data.frame(table(PM_seleccionados$identif))
PM_seleccionados[PM_seleccionados$identif %in% n_occur$Var1[n_occur$Freq > 1],]
```

#Guardar Datos

```{r}
#Se definen las variables de almacenamiento
file_path <- "~/RStudio/Dataton2017/datasets/punto_de_medida/"
file_name <- "PM_seleccionados.csv"


#Guardamos los datos finales y tratados en un fichero csv
write.csv(PM_seleccionados, paste(file_path, file_name, sep=''), row.names=FALSE)

```


