---
title: "DT_Seleccion_Outliers"
author: "Mikel Uranga"
date: "12/11/2017"
output: html_document
---


```{r}
#Se cargan las librerias necesarias
library('CausalImpact')
library(readr)
library(dplyr)
library(imputeTS)
```

#Carga de Datos

```{r}
#Se utiliza el dataset de febrero del 2016 por ser un mes sin excesivas variaciones o festividades.
DatosTrafico1602 <- read_csv("~/RStudio/Dataton2017/datasets/trafico/201602_DatosTrafico.csv", 
    col_types = cols(fecha = col_datetime(format = " %Y-%m-%d  %H:%M:%S")))
#View(DatosTrafico1704)

```

#Descripción

```{r}
summary(DatosTrafico1602)
```

#Outliers

```{r}
#outliers Carga

outlier_carga <- boxplot.stats(DatosTrafico1602$carga)$out

boxplot(DatosTrafico1602$carga, main="carga", boxwex=0.1)

mtext(paste("Outliers: ", paste(outlier_carga, collapse=", ")), cex=0.6)
```


```{r}
#Agrupamos por punto de medida 
DatosTrafico1602 %>% 
  filter(carga %in% outlier_carga ) %>%
  group_by(identif) %>% 
  dplyr::summarise(n = n()) %>% 
  arrange(desc(n))  
```


```{r}
#Guardamos los Puntos de Medida seleccionados 
PM_outliers_carga <- DatosTrafico1602 %>% 
  filter(carga %in% outlier_carga ) %>%
  group_by(identif) %>% 
  dplyr::summarise(n = n()) %>% 
  arrange(desc(n))  
```

#Guardar Datos

```{r}
#Se definen las variables de almacenamiento
file_path <- "~/RStudio/Dataton2017/datasets/punto_de_medida/"
file_name <- "201602_PM_outliers_carga.csv"


#Guardamos los datos finales y tratados en un fichero csv
write.csv(PM_outliers_carga, paste(file_path, file_name, sep=''), row.names=FALSE)

```




