---
title: "Modelos SVM"
author: "IZASKUN LOPEZ-SAMANIEGO"
date: "19 de noviembre de 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require("knitr")

ruta <-'F:/201711_dataton_opendata_madrid'
setwd(ruta)
opts_knit$set(root.dir='./')

```


## Preparación del entorno

```{r entorno}
library(randomForest)
library(data.table)
library(pROC)
library(gmodels)


source('./src/funciones_opendata.R')

```

## Cargar ficheros

    a. Cargamos el fichero con la información normalizada y añadimos los campos necesarios
    
```{r carga_ficheros}
dt.analisis <- as.data.table(read.csv('./dat/PM16_dataset.csv'))
dt.analisis <- Transformacion_variables(dt.analisis) 
dt.analisis <- dt.analisis[,list(carga, vel.med, carga.med, 
                                 #carga.15, vmed.15, 
                                 carga.30, vmed.30, 
                                 #carga.45, vmed.45,
                                 prec_norm, 
                                 #var.carga.15, var.vmed.15, 
                                 var.carga.30, var.vmed.30, 
                                 diaMes, Mes, n.festivo)]#, 
                                 #diaLunes, diaMartes, diaMiercoles,
                                 #diaJueves, diaViernes, 
                                 #diaSabado, diaDomingo)]
```

## Dividimos la muestra en casos de test y casos de training

```{r test_and_testing, echo=TRUE}

inTrain <- sample(1:nrow(dt.analisis),
                  nrow(dt.analisis)*0.8)

train.analisis  <- dt.analisis[-inTrain,]
test.analisis   <- dt.analisis[inTrain,]

```

## Test Modelo Random Forest

```{r RF, echo=TRUE}
set.seed(125)

rf.M30 <- randomForest(carga ~. , 
                       data = train.analisis,
                       ntree = 5, 
                       do.trace = T)
rf.M30
par(mfrow=c(1,31)) 
plot(rf.M30)

```

 1. Analizamos la salida teniendo en cuenta OBB como estimador razonable

```{r RF analisis}

rf.M30
plot(rf.M30)

# Revisamos la importancia de las variables
varImpPlot(rf.M30)

```   


#CALCULO RMSE
  
  a. Training

```{r RMSE Training, echo=TRUE}
predict.M30 <- predict(rf.M30, interval = "prediction")
#calculo_error(train.analisis, predict.M30)
predict.M30<-as.data.table(predict.M30)
predict.M30$fit <- predict.M30[,1]
  error <- data.table(train.analisis$carga,
                      predict.M30$fit,
                      dif = predict.M30$fit - train.analisis$carga)
  
  error[!is.na(dif), list(error=sum(as.numeric(dif))^2/.N)]
#  nrow(error[is.na(dif)])
```

  b. Test

```{r RMSE Test, echo=TRUE}
predict.M30 <- predict(rf.M30, test.analisis, interval = "prediction")
predict.M30 <- as.data.table(predict.M30)
predict.M30$fit <- predict.M30[,1]
  error <- data.table(train.analisis$carga,
                      predict.M30$fit,
                      dif = predict.M30$fit - train.analisis$carga)
  
  error[, list(error=sum(as.numeric(dif))^2/.N)]

```